name: TaskSphere CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "20.11.0"
  GO_VERSION: "1.24.0"
jobs:
  go-test:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run unit tests
      run: go test ./... -cover

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run gosec
      run: gosec ./...

  style:
    name: Go Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

    name: Go Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install linters and formatters
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install mvdan.cc/gofumpt@latest

      - name: Run golangci-lint
        working-directory: ./tasksphere-api
        run: golangci-lint run

      - name: Check Go formatting with go fmt
        working-directory: ./tasksphere-api
        run: test -z $(go fmt ./...) echo $? | grep . && exit 1 || echo "✅ Code is formatted"

  # Backend build and test
  go-backend-build-test:
    name: Go Backend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Restore Go dependencies
        working-directory: ./tasksphere-api
        run: go mod download

      - name: Build Go backend
        working-directory: ./tasksphere-api
        run: go build -o bin/app ./cmd/main.go

      - name: Run Go tests
        working-directory: ./tasksphere-api
        run: go test -cover ./...

      - name: Upload Go build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: ./tasksphere-api/bin/app
          retention-days: 2