name: TaskSphere CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "20.11.0"
  GO_VERSION: "1.24.0"
jobs:
  tasksphere-api-test:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run unit tests
      working-directory: ./tasksphere-api
      run: go test ./... -cover

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run gosec
      working-directory: ./tasksphere-api
      run: gosec ./...
      

  tasksphere-api-style:
    name: Tasksphere API Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check formatting
        working-directory: ./tasksphere-api
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./tasksphere-api
        run: staticcheck ./...

 
  tasksphere-api-build:
    name: Tasksphere API Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Restore Go dependencies
        working-directory: ./tasksphere-api
        run: go mod download

      - name: Build Go backend
        working-directory: ./tasksphere-api
        run: go build -o bin/app ./cmd/main.go

      - name: Upload Go build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tasksphere-api
          path: ./tasksphere-api/bin/app
          retention-days: 2